# Generated by Django 2.1.5 on 2019-01-24 19:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
